name: Scheduled Tests - DateTimeChecker

on:
  schedule:
    # Run tests every day at 2:00 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  scheduled-test:
    name: Daily Automated Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run comprehensive tests
        run: npm run test
      
      - name: Build application
        run: npm run build
      
      - name: Check for vulnerabilities
        run: npm audit --audit-level=moderate
      
      - name: Create test report
        if: always()
        run: |
          echo "## DateTimeChecker - Daily Test Report" >> $GITHUB_STEP_SUMMARY
          echo "**Date:** $(date)" >> $GITHUB_STEP_SUMMARY
          echo "**Status:** Tests completed" >> $GITHUB_STEP_SUMMARY
      
      - name: Notify on failure
        if: failure()
        run: |
          echo "❌ Scheduled tests failed!"
          echo "Please investigate the DateTimeChecker application."
